version: '3.8'

services:
  #--- SERVIÇO PARA RODAR TESTES ---
  test-runner:
    build: .
    command: tail -f /dev/null
    environment:
      - DB_HOST=db
      - DB_DATABASE=db_test
      - DB_USER=root
      - DB_PASSWORD=root
      - APP_ENV=test

  #--- AMBIENTE DE PRODUÇÃO ---
  producao:
    build: .
    ports:
      - "8082:80"
    # A seção 'volumes' foi removida daqui
    environment:
      - DB_HOST=db
      - DB_DATABASE=db_producao
      - DB_USER=root
      - DB_PASSWORD=root
      - APP_ENV=production

  #--- AMBIENTE DE HOMOLOGAÇÃO ---
  homologacao:
    build: .
    ports:
      - "8081:80"
    # E daqui também
    environment:
      - DB_HOST=db
      - DB_DATABASE=db_homologacao
      - DB_USER=root
      - DB_PASSWORD=root
      - APP_ENV=staging

  #--- BANCO DE DADOS ---
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_producao
      MYSQL_EXTRA_DATABASES: db_homologacao,db_test
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
