name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy-homolog:
    name: Testar e Publicar em Homologação
    runs-on: self-hosted

    steps:
      - name: 1. Clonar o repositório
        uses: actions/checkout@v3

      - name: 2. Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          # --- ESTA É A LINHA CORRIGIDA ---
          extensions: mbstring, intl, pdo_sqlite # Adicionado pdo_sqlite

      - name: 3. Instalar dependências
        run: composer install --no-interaction --optimize-autoloader

      - name: 4. Executar Testes Automatizados
        run: vendor/bin/phpunit

      - name: 5. Deploy para Homologação
        run: |
          echo "Iniciando deploy de homologação..."
          git pull
          sudo docker-compose up -d --build homologacao
          sudo docker-compose exec homologacao bin/cake migrations migrate
          echo "Deploy de homologação concluído."

  deploy-producao:
    name: Publicar em Produção (Manual)
    runs-on: self-hosted
    needs: test-and-deploy-homolog
    if: github.ref == 'refs/heads/main'

    environment:
      name: Producao
      url: http://177.44.248.63:8082

    steps:
      - name: Deploy para Produção
        uses: actions/checkout@v3 # Adicionado checkout para garantir os arquivos corretos
        with:
          ref: ${{ github.sha }} # Garante que estamos na versão exata do commit

      - name: Executar Deploy
        run: |
          echo "Iniciando deploy de produção..."
          sudo docker-compose up -d --build producao
          sudo docker-compose exec producao bin/cake migrations migrate
          echo "Deploy de produção concluído."
